core/urls.py
from django.urls import path
from .views import home, lista_funcoes, funcao_novo, funcao_update, funcao_search, funcao_delete
from .views import lista_setores, setor_novo, setor_update, setor_search, setor_delete
from .views import lista_tiporiscos, tiporisco_novo, tiporisco_update, tiporisco_delete
from .views import lista_riscos, risco_novo, risco_update, risco_delete, grupoexame_novo, grupoexame_delete
from .views import lista_exames, exame_novo, exame_update, exame_delete, gruporisco_delete
from .views import lista_grupos, grupo_novo, grupo_update, grupo_delete, grupofuncao_novo, grupofuncao_delete, gruporisco_novo
from .views import lista_empregados, empregado_novo, empregado_update, load_funcoes, load_grupos
from .views import lista_coords, coord_update, coord_novo, coord_delete
from .views import lista_atendimentos, atendimento_update, atendimento_delete, atendimento_search, atendimento_novo
from .views import atendimentorisco_novo, atendimentorisco_delete, atendimentoexame_novo, atendimentoexame_delete
from .views import rel_aso



urlpatterns = [

    path('home', home, name='home'),
    path('lista_funcoes', lista_funcoes, name='lista_funcoes'),
    path('funcao_novo', funcao_novo, name='funcao_novo'),
    path('funcao_update/<int:id>', funcao_update, name='funcao_update'),
    path('funcao_delete/<int:id>', funcao_delete, name='funcao_delete'),
    path('funcao_search', funcao_search, name='funcao_search'),

    path('lista_setores', lista_setores, name='lista_setores'),
    path('setor_novo', setor_novo, name='setor_novo'),
    path('setor_update/<int:id>', setor_update, name='setor_update'),
    path('setor_delete/<int:id>', setor_delete, name='setor_delete'),
    path('setor_search', setor_search, name='setor_search'),

    path('lista_tiporiscos', lista_tiporiscos, name='lista_tiporiscos'),
    path('tiporisco_novo', tiporisco_novo, name='tiporisco_novo'),
    path('tiporisco_update/<int:id>', tiporisco_update, name='tiporisco_update'),
    path('tiporisco_delete/<int:id>', tiporisco_delete, name='tiporisco_delete'),

    path('lista_riscos', lista_riscos, name='lista_riscos'),
    path('risco_novo', risco_novo, name='risco_novo'),
    path('risco_update/<int:id>', risco_update, name='risco_update'),
    path('risco_delete/<int:id>', risco_delete, name='risco_delete'),

    path('lista_exames', lista_exames, name='lista_exames'),
    path('exame_novo', exame_novo, name='exame_novo'),
    path('exame_update/<int:id>', exame_update, name='exame_update'),
    path('exame_delete/<int:id>', exame_delete, name='exame_delete'),

    path('lista_grupos', lista_grupos, name='lista_grupos'),
    path('grupo_novo', grupo_novo, name='grupo_novo'),
    path('grupo_update/<int:id>', grupo_update, name='grupo_update'),
    path('grupo_delete/<int:id>', grupo_delete, name='grupo_delete'),
    path('grupofuncao_novo/<int:id>', grupofuncao_novo, name='grupofuncao_novo'),
    path('grupofuncao_delete/<int:id>', grupofuncao_delete, name='grupofuncao_delete'),
    path('gruporisco_novo/<int:id>', gruporisco_novo, name='gruporisco_novo'),
    path('gruporisco_delete/<int:id>', gruporisco_delete, name='gruporisco_delete'),
    path('grupoexame_novo/<int:id>', grupoexame_novo, name='grupoexame_novo'),
    path('grupoexame_delete/<int:id>', grupoexame_delete, name='grupoexame_delete'),

    path('lista_empregados', lista_empregados, name='lista_empregados'),
    path('empregado_novo', empregado_novo, name='empregado_novo'),
    path('empregado_update/<int:id>', empregado_update, name='empregado_update'),
    path('ajax/load-funcoes', load_funcoes, name='ajax_load_funcoes'),
    path('ajax/load-grupos', load_grupos, name='ajax_load_grupos'),

    path('lista_coords', lista_coords, name='lista_coords'),
    path('coord_novo', coord_novo, name='coord_novo'),
    path('coord_update/<int:id>', coord_update, name='coord_update'),
    path('coord_delete/<int:id>', coord_delete, name='coord_delete'),

    path('lista_atendimentos', lista_atendimentos, name='lista_atendimentos'),
    path('atendimento_novo', atendimento_novo, name='atendimento_novo'),
    path('atendimento_update/<int:id>', atendimento_update, name='atendimento_update'),
    path('atendimento_search', atendimento_search, name='atendimento_search'),
    path('atendimento_delete/<int:id>', atendimento_delete, name='atendimento_delete'),
    path('atendimentorisco_novo/<int:id>', atendimentorisco_novo, name='atendimentorisco_novo'),
    path('atendimentorisco_delete/<int:id>', atendimentorisco_delete, name='atendimentorisco_delete'),

    path('atendimentoexame_novo/<int:id>', atendimentoexame_novo, name='atendimentoexame_novo'),
    path('atendimentoexame_delete/<int:id>', atendimentoexame_delete, name='atendimentoexame_delete'),
    path('rel_aso/<int:id>', rel_aso, name='rel_aso'),
]

sgo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/models.py
from django.db import models

# Create your models here.


class Funcao (models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'funcao'

class Setor (models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'setor'

class TipoRisco(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'tiporisco'

class Risco(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    tiporisco = models.ForeignKey('tiporisco', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'risco'

class Grupo(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'grupo'

class Exame(models.Model):
    nome = models.CharField(max_length=60, null=False, blank=False)
    validade = models.IntegerField(null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'exame'

class TipoExame(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'tipoexame'     

class GrupoExame(models.Model):
    grupo = models.ForeignKey('grupo', on_delete=models.PROTECT)
    exame = models.ForeignKey('exame', on_delete=models.PROTECT)
    tipoexame = models.ForeignKey('tipoexame', on_delete=models.PROTECT)

    class Meta:
        db_table = 'grupoexame'

class GrupoFuncao(models.Model):
    grupo = models.ForeignKey('grupo', on_delete=models.PROTECT)
    funcao = models.ForeignKey('funcao', on_delete=models.PROTECT)
    setor = models.ForeignKey('setor', on_delete=models.PROTECT)

    class Meta:
        db_table = 'grupofuncao'

class GrupoRisco(models.Model):
    grupo = models.ForeignKey('grupo', on_delete=models.PROTECT)
    risco = models.ForeignKey('risco', on_delete=models.PROTECT)

    class Meta:
        db_table = 'gruporisco'

class Coordenador(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    crm = models.CharField(max_length=10, null=False, blank=False)
    data_inicio = models.DateField(null=False, blank=False)
    data_fim = models.DateField(null=True, blank=True)

    class Meta:
        db_table = 'coordenador'

class Empregado(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    cpf = models.CharField(max_length=15, null=False, blank=False)
    ctps = models.CharField(max_length=20, null=False, blank=False)
    serie = models.CharField(max_length=10, null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    data_admissao = models.DateField(null=False, blank=False)
    data_demissao = models.DateField(null=True, blank=True)
    setor = models.ForeignKey('Setor', on_delete=models.PROTECT)
    funcao = models.ForeignKey('Funcao', on_delete=models.PROTECT)
    grupo = models.ForeignKey('Grupo', on_delete=models.PROTECT)

    class Meta:
        db_table = 'empregado'

class Atendimento(models.Model):
    data_atendimento = models.DateField(null=False, blank=False)
    empregado = models.ForeignKey('Empregado', on_delete=models.PROTECT)
    coordenador = models.ForeignKey('Coordenador', on_delete=models.PROTECT)
    setor = models.ForeignKey('Setor', on_delete=models.PROTECT)
    funcao = models.ForeignKey('Funcao', on_delete=models.PROTECT)
    grupo = models.ForeignKey('Grupo', on_delete=models.PROTECT)
    tipoexame = models.ForeignKey('TipoExame', on_delete=models.PROTECT)
    trabalhoaltura = models.BooleanField()
    espacoconfinado = models.BooleanField()
    apto = models.BooleanField()

    class Meta:
        db_table = 'atendimento'

class AtendimentoRisco(models.Model):
    atendimento = models.ForeignKey('Atendimento', on_delete=models.PROTECT)
    risco = models.ForeignKey('Risco', on_delete=models.PROTECT)

    class Meta:
        db_table = 'atendimentorisco'

class AtendimentoExame(models.Model):
    atendimento = models.ForeignKey('Atendimento', on_delete=models.PROTECT)
    exame = models.ForeignKey('Exame', on_delete=models.PROTECT)

    class Meta:
        db_table = 'atendimentoexame'

core/forms.py
from django.forms import ModelForm
from .models import Funcao, Exame, Risco, TipoRisco, Setor, Grupo, GrupoExame, GrupoFuncao, GrupoRisco, TipoExame
from .models import Coordenador, Empregado, Atendimento, AtendimentoExame, AtendimentoRisco


class FuncaoForm(ModelForm):
    class Meta:
        model= Funcao
        fields = '__all__'

class ExameForm(ModelForm):
    class Meta:
        model= Exame
        fields = '__all__'

class TipoExameForm(ModelForm):
    class Meta:
        model= TipoExame
        fields = '__all__'


class TipoRiscoForm(ModelForm):
    class Meta:
        model= TipoRisco
        fields = '__all__'

class RiscoForm(ModelForm):
    class Meta:
        model= Risco
        fields = '__all__'

class SetorForm(ModelForm):
    class Meta:
        model= Setor
        fields = '__all__'

class GrupoForm(ModelForm):
    class Meta:
        model= Grupo
        fields = '__all__'

class GrupoRiscoForm(ModelForm):
    class Meta:
        model= GrupoRisco
        fields = '__all__'

class GrupoExameForm(ModelForm):
    class Meta:
        model= GrupoExame
        fields = '__all__'

class GrupoFuncaoForm(ModelForm):
    class Meta:
        model= GrupoFuncao
        fields = '__all__'

class CoordenadorForm(ModelForm):
    class Meta:
        model= Coordenador
        fields = '__all__'

class EmpregadoForm(ModelForm):
    class Meta:
        model= Empregado
        fields = '__all__'

class AtendimentoForm(ModelForm):
    class Meta:
        model= Atendimento
        fields = '__all__'

class AtendimentoRiscoForm(ModelForm):
    class Meta:
        model= AtendimentoRisco
        fields = '__all__'

class AtendimentoExameForm(ModelForm):
    class Meta:
        model= AtendimentoExame
        fields = '__all__'

core/templates/core/atendimento_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">ATENDIMENTO</div>
<form class="form-horizontal" method="POST" action="{% url 'atendimento_novo' %}">
    {% csrf_token %}

    <div class="form6">
        <div class="form-group">
            <label for="funcao_id" class="control-label col-sm-3">Empregado:</label>
            <div class="col-sm-8">
                <select name="empregado_id" id="empregado_id" required style="width:75%; height:30px; border:#CCC solid 1px;">
                <option value="" selected >Selecione</option>
                {% for empregado in empregados %}
                       <option value="{{ empregado.id }}" >{{ empregado.nome }}</option>
                {% endfor %}      	
                </select> 
            </div> 
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="data_atendimento">Data:</label>
            <div class="col-sm-3">
                <input type="text" class="form-control" required id="data_atendimento" name="data_atendimento">
            </div>
        </div>

        <div class="form-group">
            <label for="funcao_id" class="control-label col-sm-3">Tipo Exame:</label>
            <div class="col-sm-8">
                <select name="tipoexame_id" id="tipoexame_id" required style="width:75%; height:30px; border:#CCC solid 1px;">
                <option value="" selected >Selecione</option>
                {% for tipoexame in tipoexames %}
                       <option value="{{ tipoexame.id }}" >{{ tipoexame.nome }}</option>
                {% endfor %}      	
                </select> 
            </div> 
        </div>

        <div class="form-group">
            <div class="form-check">       
                <label class="control-label col-sm-3" for="altura">Trabalho Altura:</label>
                <input class="col-sm-1" type="checkbox" name="altura" id="altura">
            </div>
        </div>

        <div class="form-group">
            <div class="form-check">       
                <label class="control-label col-sm-3" for="espaco">Espaço Confinado:</label>
                <input class="col-sm-1" type="checkbox" name="espaco" id="espaco">
            </div>
        </div>

        <div class="form-group">
            <div class="form-check">       
                <label class="control-label col-sm-3" for="apto">Apto para Trabalho:</label>
                <input class="col-sm-1" type="checkbox" name="apto" id="apto">
            </div>
        </div>

        
    </div> 

    {% if messages %}
        <div class="alert alert-danger">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}  

    <div class="botoes">
        <div class="form-group" style="margin:auto; margin-left:150px;">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-edit" 
                style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>                
        </div>
    </div>

</form>
{% endblock %}

core/templates/core/coord_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">COORDENADOR DE PCMSO</div>
<form name="form" id="form" class="form-horizontal" method="POST" action="{% url 'coord_novo' %}">
    {% csrf_token %}
    <div class="form5">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" required id="id_nome" name="nome">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="crm">CRM:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" maxlength="10" required id="id_crm" name="crm">
            </div>
            
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="data_inicio">Data Início:</label>
            <div class="col-sm-3">
                <input type="date" class="form-control" required id="id_data_inicio" name="data_inicio">
            </div>
            <label class="control-label col-sm-2" for="data_fim">Data Fim:</label>
            <div class="col-sm-3">
                <input type="date" class="form-control" id="id_data_fim" name="data_fim">
            </div>
        </div>

    </div> 

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>


{% endblock%}

core/templates/core/funcao_update.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">FUNÇÕES</div>
<form name="form" id="form" class="form-horizontal" method="post" action="{% url 'funcao_update' funcao.id %}">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome" value="{{ funcao.nome }}">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Alterar</span>
            </Button>                
        </div>
    </div>

    <div class="form-group">
        <a href="{% url 'funcao_delete' funcao.id %}"
        <Button type = "submit" class = "btn btn-danger btn-lg" style="float:right; margin-top:-60px;">
            <span class = "glyphicon glyphicon-edit" 
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Excluir</span>
        </Button>       
        </a>         
    </div>
</form>

{% endblock%}

core/templates/core/grupo_ajax.html
<option value="" selected >Selecione</option>
{% for g in grupos %}
    <option value="{{ g.grupo.id }}" >{{ g.grupo.nome }}</option>
{% endfor %}

core/templates/core/grupo_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">GRUPO HOMOGÊNEO</div>
<form name="form" id="form" class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>

{% endblock%}

core/templates/core/gruporisco_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">GRUPOS HOMOGÊNEOS</div>
<form name="form" id="form" class="form-horizontal" method="post" action="{% url 'gruporisco_novo' grupo.id %}">
    {% csrf_token %}
    <div class="tab">
            <ul class="nav nav-tabs">
                <li><a href="{% url 'lista_grupos' %}">Grupos</a></li>
                <li><a href="{% url 'grupofuncao_novo' grupo.id %}">Função X Setor</a></li>
                <li class="active"><a href="#">Riscos</a></li>
                <li><a href="{% url 'grupoexame_novo' grupo.id %}">Exames</a></li>
            </ul>
        </div>
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome" value="{{ grupo.nome }}">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="form1">
        <div class="form-group">
            <label for="risco_id" class="control-label col-sm-3">Risco:</label>
            <div class="col-sm-8">
                <select name="risco_id" id="risco_id" required style="width:75%; height:30px; border:#CCC solid 1px;">
                <option value="" selected >Selecione</option>
                {% for risco in riscos %}
                    <option value="{{ risco.id }}" >{{ risco.nome }}</option>
                {% endfor %}      	
                </select> 
            </div> 
        </div>

    </div>

    {% if messages %}
        <div class="alert alert-danger">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>                
        </div>
    </div>

    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>RISCO</th>
            <th width="50">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        {% for gruporisco in gruporiscos %}
        <tr>
            <td>{{ gruporisco.risco.nome }}</td>               
            <td style="width:60px; text-align: center;">
                <a href="{% url 'gruporisco_delete' gruporisco.id %}" style="color:#fff" class="btn btn-danger">
                <span class = "glyphicon glyphicon-trash"></span>
                </a>
            </td>
        </tr>
        
        {% endfor %}
        
        </tbody>
    </table>
    
</form>

{% endblock%}

core/templates/core/lista_atendimentos.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">ATENDIMENTOS</div>
<form name="form" id="form" class="form-horizontal" method="GET" action="{% url 'atendimento_search' %}">
    <div class="form5">
            <div class="form-group">
                <label class="control-label col-sm-2" for="nome">Nome:</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="nome" name="nome">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="data_atendimento">Período:</label>
                <div class="col-sm-3">
                    <input type="date" class="form-control" id="data1" name="data1">
                </div>
                <label class="control-label col-sm-1" for="data2">a</label>
                <div class="col-sm-3">
                    <input type="date" class="form-control" id="data2" name="data2">
                </div>
                
            </div>
            <div class="col-sm-1" style="float: right; margin-right: 380px;">
                <button id="search-btn" type="submit" style="color:#fff; margin-top:20px; " class="btn btn-primary"> 
                <span class = "glyphicon glyphicon-search"
                style="margin-left:5px; font-size: 12px; padding-bottom:5px;">
                </span></Button>
            </div>
        </div>
       </div>
    <div class="botoes">
        <div class="form-group">
            <a href="{% url 'atendimento_novo' %}" style="color:#fff" class="btn btn-primary"> 
            <span class = "glyphicon glyphicon-plus" id="search-btn"
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Novo
            </span></a>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
    
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>NOME</th>
                <th>TIPO DE EXAME</th>
                <th>DATA</th>
                <th>SETOR</th>
                <th>FUNÇÃO</th>
                <th width="50">&nbsp;</th>
                <th width="50">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {% for atendimento in atendimentos%}
            <tr>
                <td>{{ atendimento.empregado.nome }}</td>
                <td>{{ atendimento.tipoexame.nome }}</td>
                <td>{{ atendimento.data_atendimento|date:"d/m/Y" }}</td>
                <td>{{ atendimento.setor.nome }}</td>
                <td>{{ atendimento.funcao.nome }}</td>
                <td style="width:50px; text-align: center;">
                <a href="{% url 'rel_aso' atendimento.id %}" style="color:#fff" class="btn btn-primary">
                <span class = "glyphicon glyphicon-edit"
                style="margin-left: 5px; margin-right: 5px; font-size: 10px; padding-bottom:5px;">
                </span></a>
                </td>
                <td style="width:50px; text-align: center;">
                <a href="{% url 'atendimento_update' atendimento.id %}" style="color:#fff" class="btn btn-primary">
                <span class = "glyphicon glyphicon-print"
                style="margin-left: 5px; margin-right: 5px; font-size: 10px; padding-bottom:5px;">
                </span></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

     <div class="pagination">
        <span class="step-links">
        {% if atendimentos.has_previous %}
            <a href="?page={{ atendimentos.previous_page_number }}">
            <span class = "glyphicon glyphicon-arrow-left"
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> 
            </span></a>
        {% endif %}
        </span>

        <span>
            {{ atendimentos.number }} de {{ atendimentos.paginator.num_pages }}
        </span>

        <span>
        {% if atendimentos.has_next %}
            <a href="?page={{ cargos.next_page_number }}">
            <span class = "glyphicon glyphicon-arrow-right"
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> 
            </span></a>
        {% endif %}
        </span>
    </div>   
</form>

{% endblock%}

core/templates/core/setor_update.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">SETORES</div>
<form name="form" id="form" class="form-horizontal" method="post" action="{% url 'setor_update' setor.id %}">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome" value="{{ setor.nome }}">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Alterar</span>
            </Button>                
        </div>
    </div>

    <div class="form-group">
        <a href="{% url 'setor_delete' setor.id %}"
        <Button type = "submit" class = "btn btn-danger btn-lg" style="float:right; margin-top:-46px;">
            <span class = "glyphicon glyphicon-edit" 
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Excluir</span>
        </Button>       
        </a>         
    </div>
</form>

{% endblock%}